name: Build Datapacks

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip all packs in /packs
        run: |
          mkdir -p artifacts
          shopt -s nullglob
          for d in packs/*/ ; do
            name=$(basename "$d")
            zip -r "artifacts/${name}.zip" "$d" -x "*.git*" "*.github*" "*/.DS_Store"
          done
          ls -l artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datapacks
          path: artifacts/*.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: datapacks
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
